project_id: '511980'
base_path: /
base_url: 'https://api.crowdin.com'
preserve_hierarchy: true
files:
  - source: /src/Crowdin.Translations.Localization/*.en-US.resx
    translation: /src/Crowdin.Translations.Localization/SharedResource.%locale%.%file_extension%
